//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Norma.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Norma.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot get program information. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlankInformation {
            get {
                return ResourceManager.GetString("BlankInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Browser {
            get {
                return ResourceManager.GetString("Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color theme : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorTheme {
            get {
                return ResourceManager.GetString("ColorTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   COMMENT に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete browser caches. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteBrowserCaches {
            get {
                return ResourceManager.GetString("DeleteBrowserCaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete browser cookies. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteBrowserCookies {
            get {
                return ResourceManager.GetString("DeleteBrowserCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable change channel by mouse wheel. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisableChangeChannelByMouseWheel {
            get {
                return ResourceManager.GetString("DisableChangeChannelByMouseWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable context menu. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisableContextMenu {
            get {
                return ResourceManager.GetString("DisableContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fetched program comment (0). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FetchedComment0 {
            get {
                return ResourceManager.GetString("FetchedComment0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fetched program comments. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FetchedComments {
            get {
                return ResourceManager.GetString("FetchedComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fetched program information. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FetchedProgramInformation {
            get {
                return ResourceManager.GetString("FetchedProgramInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fetching program comments. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FetchingComments {
            get {
                return ResourceManager.GetString("FetchingComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fetching program information. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FetchingProgramInformation {
            get {
                return ResourceManager.GetString("FetchingProgramInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide footer controls. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HiddenFooterControls {
            get {
                return ResourceManager.GetString("HiddenFooterControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide header controls. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HiddenHeaderControls {
            get {
                return ResourceManager.GetString("HiddenHeaderControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide side controls. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HiddenSideControls {
            get {
                return ResourceManager.GetString("HiddenSideControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input comment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputComment {
            get {
                return ResourceManager.GetString("InputComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Licenses に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of holding comments : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NumberOfHoldingComments {
            get {
                return ResourceManager.GetString("NumberOfHoldingComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Others に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reception interval of comments : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReceptionIntervalOfComments {
            get {
                return ResourceManager.GetString("ReceptionIntervalOfComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload browser on broadcast commercials. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReloadBrowserOnBroadcastCommercials {
            get {
                return ResourceManager.GetString("ReloadBrowserOnBroadcastCommercials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reloading channel thumbnails. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReloadingThumbnail {
            get {
                return ResourceManager.GetString("ReloadingThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sampling interval of program state : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SamplingIntervalOfProgramState {
            get {
                return ResourceManager.GetString("SamplingIntervalOfProgramState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TIME に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update interval of program information : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateInervalOfProgramInformation {
            get {
                return ResourceManager.GetString("UpdateInervalOfProgramInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update interval of thumbnail :  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateInteralOfThumbnail {
            get {
                return ResourceManager.GetString("UpdateInteralOfThumbnail", resourceCulture);
            }
        }
    }
}
