//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Norma.Eta.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Norma.Eta.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Abema news/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string abema_news {
            get {
                return ResourceManager.GetString("abema_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Abema SPECIAL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string abema_special {
            get {
                return ResourceManager.GetString("abema_special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Norma について に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NG リストへ追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddToNG {
            get {
                return ResourceManager.GetString("AddToNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アニメ24 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string anime24 {
            get {
                return ResourceManager.GetString("anime24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーションはクラッシュしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationHasBeenCrash {
            get {
                return ResourceManager.GetString("ApplicationHasBeenCrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   番組情報を取得できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlankInformation {
            get {
                return ResourceManager.GetString("BlankInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データ取得に失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlankSlot {
            get {
                return ResourceManager.GetString("BlankSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラウザー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Browser {
            get {
                return ResourceManager.GetString("Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cast {
            get {
                return ResourceManager.GetString("Cast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CLUB CHANNEL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string club_channel {
            get {
                return ResourceManager.GetString("club_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーマ : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorTheme {
            get {
                return ResourceManager.GetString("ColorTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   条件 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   条件予約 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConditionalReservation {
            get {
                return ResourceManager.GetString("ConditionalReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このアイテムを削除してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメントをコピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CopyComment {
            get {
                return ResourceManager.GetString("CopyComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クラッシュレポートは {0} に出力されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrashReportPath {
            get {
                return ResourceManager.GetString("CrashReportPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + Enter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CtrlEnter {
            get {
                return ResourceManager.GetString("CtrlEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   黒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラウザーキャッシュを削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteBrowserCaches {
            get {
                return ResourceManager.GetString("DeleteBrowserCaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラウザー Cookie を削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteBrowserCookies {
            get {
                return ResourceManager.GetString("DeleteBrowserCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マウスホイールでのチャンネル変更を無効化 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisableChangeChannelByMouseWheel {
            get {
                return ResourceManager.GetString("DisableChangeChannelByMouseWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンテキストメニューを無効化 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisableContextMenu {
            get {
                return ResourceManager.GetString("DisableContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Documentary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string documentary {
            get {
                return ResourceManager.GetString("documentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ドラマ CHANNEL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string drama {
            get {
                return ResourceManager.GetString("drama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EDGE SPORT HD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string edge_sport {
            get {
                return ResourceManager.GetString("edge_sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予約の編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditRsv {
            get {
                return ResourceManager.GetString("EditRsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnterOnly {
            get {
                return ResourceManager.GetString("EnterOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   毎日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Everyday {
            get {
                return ResourceManager.GetString("Everyday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   期限 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExpiredAt {
            get {
                return ResourceManager.GetString("ExpiredAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   家族アニメ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string family_anime {
            get {
                return ResourceManager.GetString("family_anime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0 件のコメントを同期しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FetchedComment0 {
            get {
                return ResourceManager.GetString("FetchedComment0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメントを同期しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FetchedComments {
            get {
                return ResourceManager.GetString("FetchedComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   番組情報を同期しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FetchedProgramInformation {
            get {
                return ResourceManager.GetString("FetchedProgramInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメントを同期しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FetchingComments {
            get {
                return ResourceManager.GetString("FetchingComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   番組情報を同期しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FetchingProgramInformation {
            get {
                return ResourceManager.GetString("FetchingProgramInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   釣り に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fishing {
            get {
                return ResourceManager.GetString("fishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   金曜日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フッターの非表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HiddenFooterControls {
            get {
                return ResourceManager.GetString("HiddenFooterControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘッダーの非表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HiddenHeaderControls {
            get {
                return ResourceManager.GetString("HiddenHeaderControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   左側コントロールの非表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HiddenLeftControl {
            get {
                return ResourceManager.GetString("HiddenLeftControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイドコントロールの非表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HiddenSideControls {
            get {
                return ResourceManager.GetString("HiddenSideControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無視する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタム CSS を追加しています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InjectCss {
            get {
                return ResourceManager.GetString("InjectCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメントを入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputComment {
            get {
                return ResourceManager.GetString("InputComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正な日付です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDateTime {
            get {
                return ResourceManager.GetString("InvalidDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付は現在よりも大きい必要があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDateTime2 {
            get {
                return ResourceManager.GetString("InvalidDateTime2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正な正規表現です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidRegex {
            get {
                return ResourceManager.GetString("InvalidRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正規表現 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsRegex {
            get {
                return ResourceManager.GetString("IsRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーワードは空にできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeywordCannotBeBlank {
            get {
                return ResourceManager.GetString("KeywordCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ライセンス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   白 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読み込み中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   麻雀 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string mahjong {
            get {
                return ResourceManager.GetString("mahjong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   深夜アニメ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string midnight_anime {
            get {
                return ResourceManager.GetString("midnight_anime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MinutesBefore {
            get {
                return ResourceManager.GetString("MinutesBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月曜日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月曜日から金曜日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonToFri {
            get {
                return ResourceManager.GetString("MonToFri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月曜日から土曜日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonToSat {
            get {
                return ResourceManager.GetString("MonToSat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MTV HITS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string mtv_hits {
            get {
                return ResourceManager.GetString("mtv_hits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ミュートキーワード : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MuteKeywords {
            get {
                return ResourceManager.GetString("MuteKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新作アニメ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string new_anime {
            get {
                return ResourceManager.GetString("new_anime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いいえ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   なし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   まもなく、キーワード「{0}」が含まれている番組が始まります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoticeKeywordRsvBody {
            get {
                return ResourceManager.GetString("NoticeKeywordRsvBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予約キーワード通知 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoticeKeywordRsvTitle {
            get {
                return ResourceManager.GetString("NoticeKeywordRsvTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   まもなく、予約した番組「{0}」が始まります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoticeSlotRsvBody {
            get {
                return ResourceManager.GetString("NoticeSlotRsvBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予約番組通知 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoticeSlotRsvTitle {
            get {
                return ResourceManager.GetString("NoticeSlotRsvTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   まもなく、予約時間「{0}」になります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoticeTimeRsvBody {
            get {
                return ResourceManager.GetString("NoticeTimeRsvBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予約時間通知 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoticeTimeRsvTitle {
            get {
                return ResourceManager.GetString("NoticeTimeRsvTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメント保持数 : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NumberOfHoldingComments {
            get {
                return ResourceManager.GetString("NumberOfHoldingComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   なつかしアニメ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string oldtime_anime {
            get {
                return ResourceManager.GetString("oldtime_anime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お願いランキング に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string onegai_ranking {
            get {
                return ResourceManager.GetString("onegai_ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   番組表を開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenTimetable {
            get {
                return ResourceManager.GetString("OpenTimetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動作 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オプション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   部分一致 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PartialMatching {
            get {
                return ResourceManager.GetString("PartialMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完全一致 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PerfectMatching {
            get {
                return ResourceManager.GetString("PerfectMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ペット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string pet {
            get {
                return ResourceManager.GetString("pet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クラッシュレポートを送信してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PleaseSendCrashReportToMe {
            get {
                return ResourceManager.GetString("PleaseSendCrashReportToMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理が完了するまでお待ち下さい... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   後方一致 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Postfix {
            get {
                return ResourceManager.GetString("Postfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   投稿ショートカットキー : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PostKey {
            get {
                return ResourceManager.GetString("PostKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前方一致 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   番組詳細 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgramDetails {
            get {
                return ResourceManager.GetString("ProgramDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   番組 ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgramId {
            get {
                return ResourceManager.GetString("ProgramId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   番組概要 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgramSummary {
            get {
                return ResourceManager.GetString("ProgramSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   準備完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   REALITY SHOW に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string reality_show {
            get {
                return ResourceManager.GetString("reality_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメントの受信間隔 : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReceptionIntervalOfComments {
            get {
                return ResourceManager.GetString("ReceptionIntervalOfComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正規表現モード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RegexMode {
            get {
                return ResourceManager.GetString("RegexMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Norma をスタートアップに登録する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RegToStartup {
            get {
                return ResourceManager.GetString("RegToStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CM 中にブラウザーをリロード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReloadBrowserOnBroadcastCommercials {
            get {
                return ResourceManager.GetString("ReloadBrowserOnBroadcastCommercials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サムネイルをリロードしています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReloadingThumbnail {
            get {
                return ResourceManager.GetString("ReloadingThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   繰り返し間隔 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RepeatInterval {
            get {
                return ResourceManager.GetString("RepeatInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーワード予約 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RsvByKeyword {
            get {
                return ResourceManager.GetString("RsvByKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時間予約 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RsvByTime {
            get {
                return ResourceManager.GetString("RsvByTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   条件を指定して予約 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RsvCondition {
            get {
                return ResourceManager.GetString("RsvCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以下の内容で予約しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RsvConfirm {
            get {
                return ResourceManager.GetString("RsvConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予約リスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RsvList {
            get {
                return ResourceManager.GetString("RsvList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予約完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RsvSuccess {
            get {
                return ResourceManager.GetString("RsvSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   番組状態の確認間隔 : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SamplingIntervalOfProgramState {
            get {
                return ResourceManager.GetString("SamplingIntervalOfProgramState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   水曜日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シリーズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Series {
            get {
                return ResourceManager.GetString("Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シリーズ予約 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SeriesReservation {
            get {
                return ResourceManager.GetString("SeriesReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    『{0}』シリーズを予約しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SeriesReservationResult {
            get {
                return ResourceManager.GetString("SeriesReservationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shift + Enter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShiftEnter {
            get {
                return ResourceManager.GetString("ShiftEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単体 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Slot {
            get {
                return ResourceManager.GetString("Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単体予約 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlotReservation {
            get {
                return ResourceManager.GetString("SlotReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   『{0}』 を予約しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlotReservationResult {
            get {
                return ResourceManager.GetString("SlotReservationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SPACE SHOWER MUSIC に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string space_shower {
            get {
                return ResourceManager.GetString("space_shower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SPECIAL PLUS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string special_plus {
            get {
                return ResourceManager.GetString("special_plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SPECIAL PLUS 2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string special_plus2 {
            get {
                return ResourceManager.GetString("special_plus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スタッフ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartAt {
            get {
                return ResourceManager.GetString("StartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日曜日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   木曜日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトル・キーワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TitleKeyword {
            get {
                return ResourceManager.GetString("TitleKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トースト通知 : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToastNotification {
            get {
                return ResourceManager.GetString("ToastNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   火曜日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイプ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Norma のスタートアップ登録を解除する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnregFromStartup {
            get {
                return ResourceManager.GetString("UnregFromStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   番組情報の更新間隔 : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateInervalOfProgramInformation {
            get {
                return ResourceManager.GetString("UpdateInervalOfProgramInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サムネイルの更新間隔 : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateInteralOfThumbnail {
            get {
                return ResourceManager.GetString("UpdateInteralOfThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バラエティ CHANNEL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string variety {
            get {
                return ResourceManager.GetString("variety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VICE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string vice {
            get {
                return ResourceManager.GetString("vice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   視聴する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   水曜日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WORLD SPORTS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string world_sports {
            get {
                return ResourceManager.GetString("world_sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SPORTS LIVE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string world_sports_1 {
            get {
                return ResourceManager.GetString("world_sports_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   はい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヨコノリ Surf Snow Skate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string yokonori_sports {
            get {
                return ResourceManager.GetString("yokonori_sports", resourceCulture);
            }
        }
    }
}
