//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Norma.Eta.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Norma.Eta.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Abema news/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string abema_news {
            get {
                return ResourceManager.GetString("abema_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Abema SPECIAL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string abema_special {
            get {
                return ResourceManager.GetString("abema_special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Anime24 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string anime24 {
            get {
                return ResourceManager.GetString("anime24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application has been crashed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationHasBeenCrash {
            get {
                return ResourceManager.GetString("ApplicationHasBeenCrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot get program information. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlankInformation {
            get {
                return ResourceManager.GetString("BlankInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Browser {
            get {
                return ResourceManager.GetString("Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cast に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cast {
            get {
                return ResourceManager.GetString("Cast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CLUB CHANNEL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string club_channel {
            get {
                return ResourceManager.GetString("club_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color theme : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorTheme {
            get {
                return ResourceManager.GetString("ColorTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   COMMENT に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirmation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete this item? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Crash report has written to {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrashReportPath {
            get {
                return ResourceManager.GetString("CrashReportPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + Enter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CtrlEnter {
            get {
                return ResourceManager.GetString("CtrlEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete browser caches. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteBrowserCaches {
            get {
                return ResourceManager.GetString("DeleteBrowserCaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete browser cookies. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteBrowserCookies {
            get {
                return ResourceManager.GetString("DeleteBrowserCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable change channel by mouse wheel. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisableChangeChannelByMouseWheel {
            get {
                return ResourceManager.GetString("DisableChangeChannelByMouseWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable context menu. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisableContextMenu {
            get {
                return ResourceManager.GetString("DisableContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Documentary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string documentary {
            get {
                return ResourceManager.GetString("documentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DRAMA CHANNEL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string drama {
            get {
                return ResourceManager.GetString("drama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EDGE SPORT HD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string edge_sport {
            get {
                return ResourceManager.GetString("edge_sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit reservation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditRsv {
            get {
                return ResourceManager.GetString("EditRsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnterOnly {
            get {
                return ResourceManager.GetString("EnterOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Everyday に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Everyday {
            get {
                return ResourceManager.GetString("Everyday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expired at に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExpiredAt {
            get {
                return ResourceManager.GetString("ExpiredAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Family Anime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string family_anime {
            get {
                return ResourceManager.GetString("family_anime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fetched program comment (0). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FetchedComment0 {
            get {
                return ResourceManager.GetString("FetchedComment0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fetched program comments. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FetchedComments {
            get {
                return ResourceManager.GetString("FetchedComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fetched program information. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FetchedProgramInformation {
            get {
                return ResourceManager.GetString("FetchedProgramInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fetching program comments. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FetchingComments {
            get {
                return ResourceManager.GetString("FetchingComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fetching program information. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FetchingProgramInformation {
            get {
                return ResourceManager.GetString("FetchingProgramInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fishing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fishing {
            get {
                return ResourceManager.GetString("fishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Friday に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide footer controls. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HiddenFooterControls {
            get {
                return ResourceManager.GetString("HiddenFooterControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide header controls. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HiddenHeaderControls {
            get {
                return ResourceManager.GetString("HiddenHeaderControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide left side control. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HiddenLeftControl {
            get {
                return ResourceManager.GetString("HiddenLeftControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide side controls. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HiddenSideControls {
            get {
                return ResourceManager.GetString("HiddenSideControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input comment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputComment {
            get {
                return ResourceManager.GetString("InputComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid date. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDateTime {
            get {
                return ResourceManager.GetString("InvalidDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date must be greater than now. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidDateTime2 {
            get {
                return ResourceManager.GetString("InvalidDateTime2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid regular expression. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidRegex {
            get {
                return ResourceManager.GetString("InvalidRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regex? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IsRegex {
            get {
                return ResourceManager.GetString("IsRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyword に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyword cannot be blank. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeywordCannotBeBlank {
            get {
                return ResourceManager.GetString("KeywordCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Licenses に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   loading... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mahjong に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string mahjong {
            get {
                return ResourceManager.GetString("mahjong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Midnight Anime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string midnight_anime {
            get {
                return ResourceManager.GetString("midnight_anime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   minutes before. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MinutesBefore {
            get {
                return ResourceManager.GetString("MinutesBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monday に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monday to Friday に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonToFri {
            get {
                return ResourceManager.GetString("MonToFri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monday to Saturday に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MonToSat {
            get {
                return ResourceManager.GetString("MonToSat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MTV HITS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string mtv_hits {
            get {
                return ResourceManager.GetString("mtv_hits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mute keywords : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MuteKeywords {
            get {
                return ResourceManager.GetString("MuteKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New anime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string new_anime {
            get {
                return ResourceManager.GetString("new_anime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortly, program start that contains keyword of &quot;{0}&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoticeKeywordRsvBody {
            get {
                return ResourceManager.GetString("NoticeKeywordRsvBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reservation Keyword Notification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoticeKeywordRsvTitle {
            get {
                return ResourceManager.GetString("NoticeKeywordRsvTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortly, reserved program &quot;{0}&quot; start. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoticeSlotRsvBody {
            get {
                return ResourceManager.GetString("NoticeSlotRsvBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reservation Program Notification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoticeSlotRsvTitle {
            get {
                return ResourceManager.GetString("NoticeSlotRsvTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortly, your reserved time &quot;{0}&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoticeTimeRsvBody {
            get {
                return ResourceManager.GetString("NoticeTimeRsvBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reservation Time Notification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoticeTimeRsvTitle {
            get {
                return ResourceManager.GetString("NoticeTimeRsvTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of holding comments : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NumberOfHoldingComments {
            get {
                return ResourceManager.GetString("NumberOfHoldingComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oldtime Anime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string oldtime_anime {
            get {
                return ResourceManager.GetString("oldtime_anime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Onegai Ranking に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string onegai_ranking {
            get {
                return ResourceManager.GetString("onegai_ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open timetable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenTimetable {
            get {
                return ResourceManager.GetString("OpenTimetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Others に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string pet {
            get {
                return ResourceManager.GetString("pet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please send crash report. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PleaseSendCrashReportToMe {
            get {
                return ResourceManager.GetString("PleaseSendCrashReportToMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   please wait until the end of process... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Post shortcut key : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PostKey {
            get {
                return ResourceManager.GetString("PostKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Program details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgramDetails {
            get {
                return ResourceManager.GetString("ProgramDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Program ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgramId {
            get {
                return ResourceManager.GetString("ProgramId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Program summary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgramSummary {
            get {
                return ResourceManager.GetString("ProgramSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   REALITY SHOW に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string reality_show {
            get {
                return ResourceManager.GetString("reality_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reception interval of comments : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReceptionIntervalOfComments {
            get {
                return ResourceManager.GetString("ReceptionIntervalOfComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload browser on broadcast commercials. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReloadBrowserOnBroadcastCommercials {
            get {
                return ResourceManager.GetString("ReloadBrowserOnBroadcastCommercials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reloading channel thumbnails. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReloadingThumbnail {
            get {
                return ResourceManager.GetString("ReloadingThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeat interval に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RepeatInterval {
            get {
                return ResourceManager.GetString("RepeatInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   by Keywords に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RsvByKeyword {
            get {
                return ResourceManager.GetString("RsvByKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   by Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RsvByTime {
            get {
                return ResourceManager.GetString("RsvByTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reservation with the following contents. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RsvConfirm {
            get {
                return ResourceManager.GetString("RsvConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reservation list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RsvList {
            get {
                return ResourceManager.GetString("RsvList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reservation success. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RsvSuccess {
            get {
                return ResourceManager.GetString("RsvSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reserve using keyword or time. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RsvUsingKwdOrTime {
            get {
                return ResourceManager.GetString("RsvUsingKwdOrTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sampling interval of program state : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SamplingIntervalOfProgramState {
            get {
                return ResourceManager.GetString("SamplingIntervalOfProgramState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saturday に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shift + Enter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShiftEnter {
            get {
                return ResourceManager.GetString("ShiftEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SPACE SHOWER MUSIC に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string space_shower {
            get {
                return ResourceManager.GetString("space_shower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SPECIAL PLUS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string special_plus {
            get {
                return ResourceManager.GetString("special_plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SPECIAL PLUS 2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string special_plus2 {
            get {
                return ResourceManager.GetString("special_plus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Staff に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start at に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StartAt {
            get {
                return ResourceManager.GetString("StartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sunday に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thursday に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TIME に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toast Notification : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToastNotification {
            get {
                return ResourceManager.GetString("ToastNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tuesday に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update interval of program information : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateInervalOfProgramInformation {
            get {
                return ResourceManager.GetString("UpdateInervalOfProgramInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update interval of thumbnail :  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateInteralOfThumbnail {
            get {
                return ResourceManager.GetString("UpdateInteralOfThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VARIETY CHANNEL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string variety {
            get {
                return ResourceManager.GetString("variety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VICE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string vice {
            get {
                return ResourceManager.GetString("vice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Viewing details reservation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewingDRsv {
            get {
                return ResourceManager.GetString("ViewingDRsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Viewing reservation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewingRsv {
            get {
                return ResourceManager.GetString("ViewingRsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wednesday に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WORLD SPORTS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string world_sports {
            get {
                return ResourceManager.GetString("world_sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SPORTS LIVE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string world_sports_1 {
            get {
                return ResourceManager.GetString("world_sports_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YOKONORI Surf Snow Skate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string yokonori_sports {
            get {
                return ResourceManager.GetString("yokonori_sports", resourceCulture);
            }
        }
    }
}
